FROM busybox
RUN mkdir /httpd/ && \
    echo "#!/bin/sh" > /httpd/entrypoint.sh && \
    echo "/bin/busybox httpd -f -p 80 -h /httpd/html" >> /httpd/entrypoint.sh && \
    chmod 755 /httpd/entrypoint.sh && \
    mkdir /httpd/html && \
    echo "<html><head><title>Placeholder Page</title></head><body><h1>Placeholder Page</h1></body></html>" > /httpd/html/index.html
EXPOSE 80
CMD [ "/httpd/entrypoint.sh" ]
