FROM guzo/base

RUN mkdir -p /tmp/scratch && \
    cd /tmp/scratch && \
    curl -sLO https://github.com/gohugoio/hugo/releases/download/v0.55.3/hugo_0.55.3_Linux-64bit.tar.gz && \
    tar zxvf hugo_0.55.3_Linux-64bit.tar.gz && \
    cp hugo /usr/local/bin && \
    cd /tmp/ && \
    rm -rf scratch

USER ian
EXPOSE 8080
CMD hugo --help
